### PR TITLE
Updates the plugin to support webpack hooks API

### PR DESCRIPTION
**Pull request by enjoythelive1**
Even if webpack allows the magic comments to give name to hunks, that is not the best option (separation of concerns). So this pull request updates the plugin to the new Webpack version

### CODE REVIEW

**Comment by carloscarvallo** [comment]
is there any plans to merge this? @kostasmanionis

**Comment by kostasmanionis** [comment]
@carloscarvallo not planning to merge this. This plugin should no longer be used.

If magic comments aren't your jam, you can also try [output.chunkFilename](https://webpack.js.org/configuration/output/#outputchunkfilename)

**Comment by carloscarvallo** [comment]
oohhh good to know, thanks!

**Comment by kostasmanionis** [comment]
@carloscarvallo I just realised that `output.chunkFilename` won't work.

So I guess it's still worth keeping this plugin around, I'll take a look at shipping this.

**Comment by carloscarvallo** [comment]
@kostasmanionis I think magic comments is fine, otherwise great work!

**Pull request closed without merging**
